# Generated by Django 4.1 on 2022-08-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.RemoveField(
            model_name='categorias',
            name='tipo',
        ),
    ]
