# Generated by Django 4.1 on 2022-08-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_categorias_options_remove_categorias_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='produto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorias',
            name='servico',
            field=models.BooleanField(default=False),
        ),
    ]
