# Generated by Django 4.1 on 2022-10-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_servicos_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='fabricante',
        ),
    ]
