# Generated by Django 4.1 on 2022-11-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_clientes_email_alter_clientes_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente'},
        ),
    ]
