# Generated by Django 4.1 on 2022-12-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_terceiros'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('sigla', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': 'UnidadeMedida',
            },
        ),
    ]
