# Generated by Django 4.1 on 2022-12-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_unidademedida'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='und',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.unidademedida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unidademedida',
            name='sigla',
            field=models.CharField(max_length=4),
        ),
    ]
