# Generated by Django 4.1 on 2022-12-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_servicos_und_alter_unidademedida_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='und',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.unidademedida'),
            preserve_default=False,
        ),
    ]
