# Generated by Django 4.1 on 2023-01-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_produtos_und'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Cord_geografica',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='terceiros',
            name='Cord_geografica',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
