# Generated by Django 4.1 on 2023-01-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_clientes_cord_geografica_terceiros_cord_geografica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='Cord_geografica',
            new_name='cord_geografica',
        ),
        migrations.RenameField(
            model_name='terceiros',
            old_name='Cord_geografica',
            new_name='cord_geografica',
        ),
    ]
