# Generated by Django 4.1 on 2023-04-13 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('cadastros', '0019_alter_clientes_cnpj_alter_clientes_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(default=datetime.date.today)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.clientes')),
                ('terceiro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.terceiros')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Orçamento',
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produtos')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.orcamentos')),
            ],
        ),
    ]
