# Generated by Django 4.1 on 2023-04-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_orcamentos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentos',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.clientes'),
            preserve_default=False,
        ),
    ]
