# Generated by Django 4.1 on 2023-04-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_orcamentos_terceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.produtos')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.orcamentos')),
            ],
            options={
                'verbose_name': 'itemOrcamento',
            },
        ),
    ]
