# Generated by Django 4.1 on 2023-04-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_itemorcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
