# Generated by Django 4.1 on 2023-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_alter_orcamentos_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
