# Generated by Django 4.1 on 2023-04-27 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_itemorcamento_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorcamento',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastros.orcamentos'),
        ),
    ]
