# Generated by Django 4.1 on 2023-08-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0030_alter_clientes_cnpj_alter_clientes_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(blank=True, default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terceiros',
            name='cnpj',
            field=models.CharField(blank=True, default=1, max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terceiros',
            name='cpf',
            field=models.CharField(blank=True, default=1, max_length=14),
            preserve_default=False,
        ),
    ]
