# Generated by Django 4.1 on 2023-08-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0031_alter_clientes_cnpj_alter_clientes_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cord_geografica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='terceiros',
            name='cord_geografica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
