# Generated by Django 4.1 on 2023-10-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0032_alter_clientes_cord_geografica_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamentos',
            old_name='valor',
            new_name='valor_desconto',
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='desconto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemorcamentoservico',
            name='desconto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='desconto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='situacao',
            field=models.CharField(choices=[('AB', 'Aberto'), ('AN', 'Em Andamento'), ('PA', 'Pausado'), ('AR', 'Aguardando Retorno'), ('FN', 'Finalizado')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
